run:
  deadline: 5m

linters:
  enable-all: true
  disable:
    - maligned
    - interfacer
    - scopelint
    - gomoddirectives
    - nolintlint
    - exhaustivestruct
    - wrapcheck
    - varnamelen
    - golint
    - paralleltest
    - wsl
    - nosnakecase
    - deadcode
    - ifshort
    - varcheck
    - structcheck
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - exhaustruct
    - nonamedreturns
    - testpackage
    - tagliatelle
    - goerr113
    - depguard
    - revive
    - forbidigo
    - inamedparam
    - ireturn
    - testifylint

linters-settings:
  funlen:
    lines: 90
    statements: 60
